<a href="https://colab.research.google.com/github/kgupta55/Big-data/blob/main/assignment2_31_01_24_202301030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,6,4,5])
print(np.flip(a))



[5 4 6 3 2 1]


In [ ]:
b=np.array([[1,2],[3,4]])
c=np.array([[1,2],[3,4]])
print(b==c)


[[ True  True]
 [ True  True]]


In [ ]:
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])

counts = np.bincount(x)  # Count occurrences of each element
most_frequent_value = counts.argmax()  # Find the index of the maximum count
indices = np.where(x == most_frequent_value)[0] # Find all indices of the most frequent value

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

# Question3 2nd Part
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

counts = np.bincount(y)
most_frequent_value = counts.argmax()
indices = np.where(y == most_frequent_value)[0]

print(f"Most frequent value: {most_frequent_value}")
print(f"Indices: {indices}")

Most frequent value: 1
Indices: [0 5 7 8 9]
Most frequent value: 1
Indices: [0 1 2]


In [ ]:
#Question4
import numpy as np

x = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(x)

sum_matrix = np.sum(x)
print("\n the sum of matrix is", sum_matrix)

sum_row = x.sum(axis = 1)
print("\n the sum of all rows are:", sum_row)

sum_col = x.sum(axis = 0)
print("\n the sum of all columns are:", sum_col)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

 the sum of matrix is 45

 the sum of all rows are: [[14]
 [16]
 [15]]

 the sum of all columns are: [[20  9 16]]
